jwt:
  token:
    secret:
      "jwtappcourse"
    expired:
      1800_000
spring:
  datasource:
    url:
      jdbc:postgresql://localhost:5432/veterinary
    username:
      postgres
    password:
      root
  jpa:
    generate-ddl:
      true