server:
  port:
    8080
jwt:
  token:
    secret:
      "jwtappcourseproject"
    expired:
      1800_000
spring:
  datasource:
    url:
      jdbc:postgresql://localhost:5432/veterinary
    username:
      postgres
    password:
      root
  jpa:
    database-platform:
      org.hibernate.dialect.PostgreSQLDialect
    generate-ddl:
      true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation:
              true
        temp:
          use_jdbc_metadata_defaults:
            false
  main:
    allow-bean-definition-overriding:
      true